#!/usr/bin/env python3
"""
Generate benchmarks/PERFORMANCE.md from all benchmark_results_*.csv files.

Usage (from repo root):
    python3 scripts/generate_perf_doc.py
"""

import csv
import glob
from datetime import datetime
from pathlib import Path


def _load(path):
    """Return (gpu_label, rows). Handles legacy CSVs without a 'gpu' column."""
    rows = list(csv.DictReader(open(path)))
    if not rows:
        return None, []
    if "gpu" in rows[0] and rows[0]["gpu"]:
        gpu = rows[0]["gpu"]
    else:
        stem = Path(path).stem  # "benchmark_results" or "benchmark_results_<GPU>"
        suffix = stem.replace("benchmark_results", "").lstrip("_")
        gpu = suffix if suffix else "Laptop GPU (L500)"
    return gpu, rows


def _fmt(val_str, std_str=None):
    try:
        val = int(round(float(val_str)))
    except (ValueError, TypeError):
        return "—"
    if std_str:
        try:
            s = float(std_str)
            if s >= 0.5:
                return f"{val:,} ±{int(round(s))}"
        except (ValueError, TypeError):
            pass
    return f"{val:,}"


def _section(gpu, rows):
    has_std = "time_ms_std" in rows[0]
    n_outer = rows[0].get("n_outer_runs", "")

    lines = [f"### {gpu}"]
    if n_outer:
        lines.append(f"*{n_outer} outer runs × 5 inner timed runs per measurement.*")
    lines.append("")

    data = {}
    for r in rows:
        data[(r["model"], r["option_type"], r["engine"], int(r["n_paths"]))] = r

    option_rows = [
        ("GBM",    "European", "GBM European"),
        ("GBM",    "Asian",    "GBM Asian"),
        ("GBM",    "Barrier",  "GBM Barrier (Up-and-Out)"),
        ("Heston", "European", "Heston European"),
        ("Heston", "Asian",    "Heston Asian"),
        ("Heston", "Barrier",  "Heston Barrier (Up-and-Out)"),
    ]

    lines += [
        "| Option Type | CPU 1M (ms) | GPU 1M (ms) | GPU 10M (ms) | Speedup |",
        "|-------------|------------:|------------:|-------------:|--------:|",
    ]
    for model, opt, label in option_rows:
        rc  = data.get((model, opt, "CPU", 1_000_000))
        rg  = data.get((model, opt, "GPU", 1_000_000))
        rg10 = data.get((model, opt, "GPU", 10_000_000))

        std_c  = rc.get("time_ms_std")  if (rc  and has_std) else None
        std_g  = rg.get("time_ms_std")  if (rg  and has_std) else None

        cpu_s  = _fmt(rc["time_ms_median"],  std_c)  if rc   else "—"
        gpu_s  = _fmt(rg["time_ms_median"],  std_g)  if rg   else "—"
        g10_s  = _fmt(rg10["time_ms_median"])         if rg10 else "—"

        if rc and rg:
            s = float(rc["time_ms_median"]) / float(rg["time_ms_median"])
            spd = f"**{s:.1f}×**"
        else:
            spd = "—"

        lines.append(f"| {label} | {cpu_s} | {gpu_s} | {g10_s} | {spd} |")

    lines.append("")
    return "\n".join(lines)


def main():
    repo_root = Path(__file__).parent.parent
    out_path  = repo_root / "benchmarks" / "PERFORMANCE.md"

    # Collect: legacy file first, then per-hardware files sorted by GPU name
    legacy = repo_root / "benchmark_results.csv"
    named  = sorted(glob.glob(str(repo_root / "benchmark_results_*.csv")))
    all_csvs = (([str(legacy)] if legacy.exists() else []) + named)

    if not all_csvs:
        print("No benchmark_results*.csv files found.", file=sys.stderr)
        import sys; sys.exit(1)

    gpu_names, sections, sources = [], [], []
    for path in all_csvs:
        gpu, rows = _load(path)
        if not rows:
            continue
        gpu_names.append(gpu)
        sources.append(Path(path).name)
        sections.append(_section(gpu, rows))

    hw_table = (
        ["| GPU | Source file |", "|-----|------------|"]
        + [f"| {g} | `{f}` |" for g, f in zip(gpu_names, sources)]
    )

    body_parts = []
    for sec in sections:
        body_parts.append(sec)
        body_parts.append("---")
        body_parts.append("")

    doc = "\n".join([
        "# Performance Results",
        "",
        f"*Auto-generated by `scripts/generate_perf_doc.py` — {datetime.now().strftime('%Y-%m-%d')}.*",
        "",
        "All timings in milliseconds.  "
        "CPU: single core, GCC 13.3, -O3.  "
        "252 steps, spot=100, strike=105, r=5%, σ=20%, T=1yr.",
        "",
        "## Hardware tested",
        "",
        *hw_table,
        "",
        "---",
        "",
        *body_parts,
    ])

    out_path.parent.mkdir(exist_ok=True)
    out_path.write_text(doc)
    print(f"Written: {out_path}")
    print(f"  Hardware sections: {', '.join(gpu_names)}")


if __name__ == "__main__":
    main()
